apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: buckets.zion.com
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: zion.com/v1alpha1
    kind: Bucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta2
        kind: Bucket
        metadata:
          labels:
            crossplane.io/claim-name: bucket
        spec:
          forProvider:
            bucket: ""  # Patched below
            region: ""  # Patched below
            objectLockEnabled: true
            tags: {}    # Patched below
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "spec.forProvider.bucket"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.tags"
          toFieldPath: "spec.forProvider.tags"
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "metadata.labels.testing.upbound.io/example-name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"

    - name: bucket-acl
      base:
        apiVersion: s3.aws.upbound.io/v1beta2
        kind: BucketACL
        spec:
          forProvider:
            acl: private
            region: ""
            bucketSelector:
              matchLabels:
                testing.upbound.io/example-name: ""
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "spec.forProvider.bucketSelector.matchLabels.testing.upbound.io/example-name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"

    - name: bucket-logging
      base:
        apiVersion: s3.aws.upbound.io/v1beta2
        kind: BucketLogging
        spec:
          forProvider:
            region: ""
            targetPrefix: log/
            bucketSelector:
              matchLabels:
                testing.upbound.io/example-name: ""
            targetBucketSelector:
              matchLabels:
                testing.upbound.io/example-name: ""
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "spec.forProvider.bucketSelector.matchLabels.testing.upbound.io/example-name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "spec.forProvider.targetBucketSelector.matchLabels.testing.upbound.io/example-name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"

    - name: bucket-public-access-block
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPublicAccessBlock
        spec:
          forProvider:
            region: ""
            blockPublicAcls: true
            blockPublicPolicy: true
            bucketSelector:
              matchLabels:
                testing.upbound.io/example-name: ""
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.blockPublicAcls"
          toFieldPath: "spec.forProvider.blockPublicAcls"
        - fromFieldPath: "spec.blockPublicPolicy"
          toFieldPath: "spec.forProvider.blockPublicPolicy"
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "spec.forProvider.bucketSelector.matchLabels.testing.upbound.io/example-name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
