apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: buckets.zion.com
spec:
  group: zion.com
  names:
    kind: Bucket
    plural: buckets
  claimNames:
    kind: BucketClaim
    plural: bucketclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                region:
                  type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
                blockPublicAcls:
                  type: boolean
                blockPublicPolicy:
                  type: boolean
