apiVersion: v2
name: micro-service-example
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: micro-service
    alias: service-1
    version: 0.1.0
    repository: "file://../../helm-charts/micro-service"
